export const videos = [
  {
    _id: "oI-M8T-UsNo",
    title: "How alcohol damages liver [लिवर कैसे खराब होता है?]  ",
    views: "522K",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "2 months ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "दिमाग का काम है सोचना. दिल का काम है खून को पंप करना. पेट और आंतों का खाने को पचाना. लेकिन लिवर का काम क्या है? लिवर दरअसल ऑफिस के उस कर्मचारी जैसा है जिसके बारे में कोई ठीक से नहीं जानता कि वो करता क्या है ",
  },
  {
    _id: "FwxSm6EdJUU",
    title: "9 Majedaar Futuristic Smartphone Tech !",
    views: "1M",
    creator: "Tech burner",
    subscribers: "8.55M",
    releaseTime: "7 months ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLSLzBlLalLFEXgvGHr6f9yBm9Y8PrJMXZC_hxTTlQ=s88-c-k-c0x00ffffff-no-rj",
    description: " Bhavishya ke Smartphones !"
  },
  {
    _id: "LlvBzyy-558",
    title: "React Hooks Course - All React Hooks Explained",
    views: "387K",
    creator: "Pedro Tech",
    subscribers: "70.3K",
    releaseTime: "2 years ago",
    genre: "programming",
    logoURL: "https://yt3.ggpht.com/tLOaVyDRQq46qga99PFlP9b3PRcni8gBJepNOecsgIdADpxU10p6w0VD-fZ8VvtqeldN6IHYOj0=s88-c-k-c0x00ffffff-no-rj",
    description: "In this video I will teach you guys every single core hook from React!"
  },
  {
    _id: "IPFVwMT2US0",
    title: "Switched To iPhone After 10Yrs of Android .. What Changes ? Issues ?",
    views: "24K",
    creator: "sarcastic Sindhi",
    subscribers: "200K",
    releaseTime: "1 year ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/hnr_6cS2ZzjmZCJd7Kx_P_ajdO9zc3mDM-DiHFCIN-qnVY15Umfyi9Y0nR0XD_4ErQAw4YZfQ_w=s88-c-k-c0x00ffffff-no-rj",
    description: "Meesho Maha Indian Savings Sale from 4th-6th March, get up to 80% OFF"
  },
  {
    _id: "R3rgABGYsz0",
    title: "5 Crazy Free Android Apps You've Never Heard of 🤯 * Very Useful *",
    views: "1M",
    creator: "Technology gyan",
    subscribers: "11.2M",
    releaseTime: "2 months ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/tC7T8-4MvARqycrxkYbYQh5ygYMjqIn4ET9s-OAjmWeM349qscepubONTcBvb_vG43jwW_Xi_g=s88-c-k-c0x00ffffff-no-rj",
    description: "5 Crazy Free Android Apps  useful apps 2022 : is video mein mene students gamers gaming ke liye aur kuch useful android apps bataye hai"
  },
  {
    _id: "aWM3i-ISleo",
    title: "शहर में जंगल को साकार करती इमारतें [Tiny forests in the city - A cool idea!]",
    views: "600K",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "1 year ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "शहरी क्षेत्रों में छोटे जंगल बनाना जापान में शुरु हुआ था. यह विचार अब यूरोप में पकड़ में भी गति पकड़ रहा है. कंपनियां और स्कूल इसके लिए आगे आ रहे हैं.",

  },
  {
    _id: "QX3iigjsqoA",
    title: "700 Bugs निकालने वाले इस Hacker की कहानी 👨‍💻🤑 | Ankit Singh | Josh Talks Hindi",
    views: "24K",
    creator: "जोश Talks",
    subscribers: "7.4M",
    releaseTime: "5 months ago",
    genre: "जोश Talks",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLRByBdniuSdNa97O-CRq9fv1xUm6ZKmpqcmrFZSkQ=s88-c-k-c0x00ffffff-no-rj",
    description: "ज़िन्दगी सिर्फ एक है! क्या आप करना चाहते है कुछ बड़ा? अपने जोश स्पीकर 'अंकित सिंह जी' से बात करे, जहाँ वो आप में से कुछ चुनिंदा लोगों के सवालों के जवाब देंगे और बाकी आप सभी लोग उनके जवाबों को सुन सकेंगे,"
  },
  {
    _id: "OzQmbyaidbY",
    title: "7 Majedaar Gadgets I Bought Online !",
    views: "3.7M",
    creator: "Tech burner",
    subscribers: "8.55M",
    releaseTime: "1 months ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLSLzBlLalLFEXgvGHr6f9yBm9Y8PrJMXZC_hxTTlQ=s88-c-k-c0x00ffffff-no-rj",
    description: "Mast Gadgets try kare jaa rahe hain doston!"
  },
  {
    _id: "jN6BJpW7QZ4",
    title: "अब रोशनी नहीं, अंधेरे की जरूरत है [What is Light Pollution]",
    views: "491K",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "8 months ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "जब से बिजली के बल्ब का आविष्कार हुआ है, दुनिया में जगमग लगातार बढ़ रही है. लेकिन रात के समय में कृत्रिम रोशनी की वजह से अब समस्याएं होने लगी हैं.",

  },
  {
    _id: "A45Zg8YXC8M",
    title: "जानो बड़ा Business बनाने का सबसे ज़रूरी नियम 🤨| Ashneer Grover | Josh Talks Hindi",
    views: "2.7M",
    creator: "जोश Talks",
    subscribers: "7.4M",
    releaseTime: "6 months ago",
    genre: "जोश Talks",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLRByBdniuSdNa97O-CRq9fv1xUm6ZKmpqcmrFZSkQ=s88-c-k-c0x00ffffff-no-rj",
    description: "हमारे आज के speaker है Entrepreneurship के क्षेत्र में अपनी अलग पहचान रखने वाले BharatPe के Founder & Managing Director Ashneer Grover जी; जिनकी कहानी लक्ष्य को पाने के लिए की जाने वाली असीमित मेहनत,लगन और जुनून का जीता जागता उत्तम उदाहरण है। "
  },
  {
    _id: "B4n6s-onn-4",
    title: "मानव बन रहा है दानव, खुद देखिए [Wildlife trafficking in Peru]",
    views: "10M",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "6 months ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "दक्षिण अमेरिकी देश पेरू के एक इलाके में तमाम पाबंदियों और कोशिशों के बावजूद दुर्लभ किस्म के जीवों का शिकार नहीं रुक रहा है. अब भी विलुप्त होने की कगार पर जा पहुंचे जानवरों को जिंदा या मुर्दा बाजारों में देखा जा सकता है",

  },
  {
    _id: "WV2Vr7zaM3w",
    title: "करोड़ों का Business इस Entrepreneur Motivation, Skills से बनेगा🤑 | Dilkhush Kumar | Josh Talks Hindi",
    views: "6M",
    creator: "जोश Talks",
    subscribers: "7.4M",
    releaseTime: "9 months ago",
    genre: "जोश Talks",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLRByBdniuSdNa97O-CRq9fv1xUm6ZKmpqcmrFZSkQ=s88-c-k-c0x00ffffff-no-rj",
    description: "अपना नेटवर्क बनाने और समुदाय से ज्ञान प्राप्त करने के लिए GAME के Facebook समूह Entrepreneurs Network में शामिल हों।"
  },
  {
    _id: "efWxaA5R6A4",
    title: "The Mastery Manual by Robin Sharma Audiobook | Book Summary in Hindi",
    views: "62K",
    creator: "Readers Book Club",
    subscribers: "1.32M",
    releaseTime: "1 months ago",
    genre: "book summary",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLTaD4995he8CQYqjhqN9tnT339rvEoPS-23SDq_tg=s88-c-k-c0x00ffffff-no-rj",
    description: "Download Kuku FM - https://kukufm.sng.link/Apksi/5ayr/ia6d 50% discount for 1st 250 Users - Use Coupon Code RBC50"
  },
  {
    _id: "w7ejDZ8SWv8",
    title: "React JS Crash Course",
    views: "2.3M",
    creator: "Traversy Media",
    subscribers: "1.86M",
    releaseTime: "2 years ago",
    genre: "programming",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLSxHOOxxa9Af8Bfb2XMop3lm4tor9bViWiC-d5aaw=s88-c-k-c0x00ffffff-no-rj",
    description: "Get started with React in this crash course. We will be building a task tracker app and look at components, props, state, hooks, working with an API and more."
  },
  {
    _id: "pLQfNfrAd5Y",
    title: "5 Ways to Be a Dangerously Powerful Man! खतरनाक ताकतवर आदमी बनना सीखो | Yebook",
    views: "218K",
    creator: "yebook",
    subscribers: "3.51M",
    releaseTime: "1 month ago",
    genre: "book summary",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLR0eK4VnxLn62ckwe3vENIXKtNmV1LZnWTbeTN4=s88-c-k-c0x00ffffff-no-rj",
    description: "Jordan Peterson kehte hain ki ek achha insaan harmless nahi hota balki ek achha insaan wo hota hai jo bohot dangerous ho lekin wo kisi ko nuksaan na pahunchana choose kare. "
  },
  {
    _id: "DTkuwMSpP20",
    title: "BRAIN RULES Book Summary in Hindi by John Medina | 12 Brain Rules That Will Change Your Life",
    views: "6M",
    creator: "Rewirs",
    subscribers: "1.16M",
    releaseTime: "2 years ago",
    genre: "book summary",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLS6b6sr0NdZxNuD5ZPPNtZzPWo1HX7Ie8JK0FZyjw=s88-c-k-c0x00ffffff-no-rj",
    description: "In this video we will summaries the book Brain Rules which share how our brain science works and influence the we think or teach children or adults."
  },
  {
    _id: "_otuQsbVIjc",
    title: "Was Karna the cause of Mahabharata? | Karna accepts his defeat",
    views: "395K",
    creator: "Spiritual Enigma",
    subscribers: "17.8K",
    releaseTime: "1 years ago",
    genre: "Krishna",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQ8bnIoW5cMfTGd_l03UdE4M2xplZSCstEnylzY=s88-c-k-c0x00ffffff-no-rj",
    description: "Hare Krishna, Do you think Karna had not supported Duryodhana this DHARMYUDH would not have happened? Watch the entire video to find out!!!"
  },
  {
    _id: "5-V0-y1iP3Q",
    title: "React Native vs Flutter | Which one should you Learn in 2022 ?",
    views: "103K",
    creator: "APNA COLLEGE",
    subscribers: "1.69M",
    releaseTime: "2 months ago",
    genre: "programming",
    logoURL: "https://yt3.ggpht.com/O12gYmCwBASezJpxddXOj1PEirMgxCGX2gOiJ3plomaK4E0K1hr_iobbQEWz1e4QVMflTmug=s88-c-k-c0x00ffffff-no-rj",
    description: "Hare Krishna, Do you think Karna had not supported Duryodhana this DHARMYUDH would not have happened? Watch the entire video to find out!!!"
  },
  {
    _id: "JJ0O5sgFqx0",
    title: "Mindset by Carol Dweck Audiobook | Book Summary in Hindi",
    views: "1.2M",
    creator: "Readers Book Club",
    subscribers: "1.32M",
    releaseTime: "2 years ago",
    genre: "book summary",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLTaD4995he8CQYqjhqN9tnT339rvEoPS-23SDq_tg=s88-c-k-c0x00ffffff-no-rj",
    description: "This book is Mindset written by Carol Dweck Audiobook. Its a Book Summary in Hindi with Animated Book Review. Learn about Business, Parenting, School& Relationship."
  },
  {
    _id: "57opnXZ8OJQ",
    title: "Who am I By Lord Krishna Revealed in Bhagvad Gita in Hindi",
    views: "199K",
    creator: "BRIGHT KNOWLEDGE",
    subscribers: "25K",
    releaseTime: "4 years ago",
    genre: "Krishna",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLTEweqZbmChmw9C-tnlpklqiXZFnK5l4XIw20ak=s88-c-k-c0x00ffffff-no-rj",
    description: "Hare Krishna, Do you think Karna had not supported Duryodhana this DHARMYUDH would not have happened? Watch the entire video to find out!!!"
  },
];