export const videos = [
  {
    _id: "oI-M8T-UsNo",
    title: "How alcohol damages liver [लिवर कैसे खराब होता है?]  ",
    views: "522K",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "2 months ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "दिमाग का काम है सोचना. दिल का काम है खून को पंप करना. पेट और आंतों का खाने को पचाना. लेकिन लिवर का काम क्या है? लिवर दरअसल ऑफिस के उस कर्मचारी जैसा है जिसके बारे में कोई ठीक से नहीं जानता कि वो करता क्या है ",
  },
  {
    _id: "qkxuFKqJXWY",
    title: "Roommate - Stand Up Comedy Ft. Anubhav Singh Bassi",
    views: "50M",
    creator: "Anubhav Singh Bassi",
    subscribers: "3.59M",
    releaseTime: "1 Year ago",
    genre: "Stand Up",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLS7IEPwzVpf3MOKIBHsLlIIG_UTH7CKO2iKYNxw4A=s88-c-k-c0x00ffffff-no-rj",
    description: "MY FOURTH STAND UP VIDEO IS HERE! DO WRITE YOUR ROOMMATE EXPERIENCES IN COMMENTS AND SHARE WITH YOUR FRIENDS.",
  },
  {
    _id: "FwxSm6EdJUU",
    title: "9 Majedaar Futuristic Smartphone Tech !",
    views: "1M",
    creator: "Tech burner",
    subscribers: "8.55M",
    releaseTime: "7 months ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLSLzBlLalLFEXgvGHr6f9yBm9Y8PrJMXZC_hxTTlQ=s88-c-k-c0x00ffffff-no-rj",
    description: " Bhavishya ke Smartphones !"
  },
  {
    _id: "LlvBzyy-558",
    title: "React Hooks Course - All React Hooks Explained",
    views: "387K",
    creator: "Pedro Tech",
    subscribers: "70.3K",
    releaseTime: "2 years ago",
    genre: "programming",
    logoURL: "https://yt3.ggpht.com/tLOaVyDRQq46qga99PFlP9b3PRcni8gBJepNOecsgIdADpxU10p6w0VD-fZ8VvtqeldN6IHYOj0=s88-c-k-c0x00ffffff-no-rj",
    description: "In this video I will teach you guys every single core hook from React!"
  },
  {
    _id: "IPFVwMT2US0",
    title: "Switched To iPhone After 10Yrs of Android .. What Changes ? Issues ?",
    views: "24K",
    creator: "sarcastic Sindhi",
    subscribers: "200K",
    releaseTime: "1 year ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/hnr_6cS2ZzjmZCJd7Kx_P_ajdO9zc3mDM-DiHFCIN-qnVY15Umfyi9Y0nR0XD_4ErQAw4YZfQ_w=s88-c-k-c0x00ffffff-no-rj",
    description: "Meesho Maha Indian Savings Sale from 4th-6th March, get up to 80% OFF"
  },
  {
    _id: "R3rgABGYsz0",
    title: "5 Crazy Free Android Apps You've Never Heard of 🤯 * Very Useful *",
    views: "1M",
    creator: "Technology gyan",
    subscribers: "11.2M",
    releaseTime: "2 months ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/tC7T8-4MvARqycrxkYbYQh5ygYMjqIn4ET9s-OAjmWeM349qscepubONTcBvb_vG43jwW_Xi_g=s88-c-k-c0x00ffffff-no-rj",
    description: "5 Crazy Free Android Apps  useful apps 2022 : is video mein mene students gamers gaming ke liye aur kuch useful android apps bataye hai"
  },
  {
    _id: "AU4Nct1lEVU",
    title: "Kanpur & River Ganga - Stand Up Comedy by Harsh Gujral",
    views: "17M",
    creator: "Harsh gujral",
    subscribers: "1.52M",
    releaseTime: "2 Year ago",
    genre: "Stand Up",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLTuDOpO2Vc50eR-mu8HjPzDXwnZkqUW_ZDCoQQGCg=s88-c-k-c0x00ffffff-no-rj",
    description: "MY THIRD STAND UP COMEDY VIDEO IS HERE! Every Group has a Kanpuriya friend tag your Kanpuriya friends! ",
  },
  {
    _id: "aWM3i-ISleo",
    title: "शहर में जंगल को साकार करती इमारतें [Tiny forests in the city - A cool idea!]",
    views: "600K",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "1 year ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "शहरी क्षेत्रों में छोटे जंगल बनाना जापान में शुरु हुआ था. यह विचार अब यूरोप में पकड़ में भी गति पकड़ रहा है. कंपनियां और स्कूल इसके लिए आगे आ रहे हैं.",
  },
  {
    _id: "OzQmbyaidbY",
    title: "7 Majedaar Gadgets I Bought Online !",
    views: "3.7M",
    creator: "Tech burner",
    subscribers: "8.55M",
    releaseTime: "1 months ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLSLzBlLalLFEXgvGHr6f9yBm9Y8PrJMXZC_hxTTlQ=s88-c-k-c0x00ffffff-no-rj",
    description: "Mast Gadgets try kare jaa rahe hain doston!"
  },
  {
    _id: "LfgJWr-SGxQ",
    title: "Sundeep Sharma Stand-up -Father Knows Better",
    views: "18M",
    creator: "Sundeep Sharma",
    subscribers: "1.52M",
    releaseTime: "3 Year ago",
    genre: "Stand Up",
    logoURL: "https://yt3.ggpht.com/sv9ORleTASeGsaplJd5xkgQViEk5BdmkyiWZfR0NKXRASqbcVbnJ0DDms1kBqLS5X-ZGeuW0=s88-c-k-c0x00ffffff-no-rj",
    description: "This video is my tribute to my late father Shri Hariom Sharma, an honest and upright farmer who sold tea outside his school to pay for his school fee and went on to pursue post graduation and got ",
  },
  {
    _id: "eKqY-oP1d_Y",
    title: "How to Start Coding? Learn Programming for Beginners",
    views: "1.3M",
    creator: "Apna College",
    subscribers: "1.76M",
    releaseTime: "6 months ago",
    genre: "programming",
    logoURL: "https://yt3.ggpht.com/O12gYmCwBASezJpxddXOj1PEirMgxCGX2gOiJ3plomaK4E0K1hr_iobbQEWz1e4QVMflTmug=s88-c-k-c0x00ffffff-no-rj",
    description: "🔥Java Placement Course : https://www.youtube.com/watch?v=yRpLl...🔥Complete C++ Placement Course (Data Structures+Algorithm) :"
  },
  {
    _id: "jN6BJpW7QZ4",
    title: "अब रोशनी नहीं, अंधेरे की जरूरत है [What is Light Pollution]",
    views: "491K",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "8 months ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "जब से बिजली के बल्ब का आविष्कार हुआ है, दुनिया में जगमग लगातार बढ़ रही है. लेकिन रात के समय में कृत्रिम रोशनी की वजह से अब समस्याएं होने लगी हैं.",
  },
  {
    _id: "w7ejDZ8SWv8",
    title: "React JS Crash Course",
    views: "2.3M",
    creator: "Traversy Media",
    subscribers: "1.86M",
    releaseTime: "2 years ago",
    genre: "programming",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLSxHOOxxa9Af8Bfb2XMop3lm4tor9bViWiC-d5aaw=s88-c-k-c0x00ffffff-no-rj",
    description: "Get started with React in this crash course. We will be building a task tracker app and look at components, props, state, hooks, working with an API and more."
  },
  {
    _id: "B4n6s-onn-4",
    title: "मानव बन रहा है दानव, खुद देखिए [Wildlife trafficking in Peru]",
    views: "10M",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "6 months ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "दक्षिण अमेरिकी देश पेरू के एक इलाके में तमाम पाबंदियों और कोशिशों के बावजूद दुर्लभ किस्म के जीवों का शिकार नहीं रुक रहा है. अब भी विलुप्त होने की कगार पर जा पहुंचे जानवरों को जिंदा या मुर्दा बाजारों में देखा जा सकता है",
  },
  {
    _id: "z12bz7adLKI",
    title: "Waxing - Stand Up Comedy ft. Anubhav Singh Bassi",
    views: "40M",
    creator: "Anubhav Singh Bassi",
    subscribers: "3.59M",
    releaseTime: "3 Year ago",
    genre: "Stand Up",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLS7IEPwzVpf3MOKIBHsLlIIG_UTH7CKO2iKYNxw4A=s88-c-k-c0x00ffffff-no-rj",
    description: "MY SECOND STAND UP VIDEO IS HERE! DO WRITE YOUR EXPERIENCES OF 'BEING STRONG' IN COMMENTS.",
  },
  {
    _id: "5-V0-y1iP3Q",
    title: "React Native vs Flutter | Which one should you Learn in 2022 ?",
    views: "103K",
    creator: "APNA COLLEGE",
    subscribers: "1.69M",
    releaseTime: "2 months ago",
    genre: "programming",
    logoURL: "https://yt3.ggpht.com/O12gYmCwBASezJpxddXOj1PEirMgxCGX2gOiJ3plomaK4E0K1hr_iobbQEWz1e4QVMflTmug=s88-c-k-c0x00ffffff-no-rj",
    description: "Hare Krishna, Do you think Karna had not supported Duryodhana this DHARMYUDH would not have happened? Watch the entire video to find out!!!"
  },
  {
    _id: "OCkbJNcddD8",
    title: "Tum Husn Pari | Zakir Khan | Stand Up-Comedy | Sukha Poori 2",
    views: "18M",
    creator: "Zakir Khan",
    subscribers: "7.04M",
    releaseTime: "2 Year ago",
    genre: "Stand Up",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQ-IPFEzpiA0AqSSeK7ZiBWUfrG4a3OZar2p3tXNQ=s88-c-k-c0x00ffffff-no-rj",
    description: "MY THIRD STAND UP VIDEO IS HERE! DO WRITE YOUR EXPERIENCES OF 'BEING STRONG' IN COMMENTS.",
  },
  {
    _id: "omARBqolqfo",
    title: "Sehat Talk with Isha Bhatia Sanan, Ep. 18: Which is the best superfood for brain?",
    views: "2M",
    creator: "DW हिन्दी",
    subscribers: "3.22M",
    releaseTime: "1 months ago",
    genre: "DW हिन्दी",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLQjtG818-C6gHmcCaTRNmrl4Q4hk4WPLyLLifk0ng=s68-c-k-c0x00ffffff-no-rj",
    description: "स्कूल या कॉलेज के टेस्ट शुरू होते ही, माएं बच्चों को बादाम-अखरोट खिलाना शुरू कर देती हैं. लेकिन क्या इनसे सच में दिमाग तेज चलता है? और अगर हां, तो आखिर इनमें ऐसा क्या होता है कि दिमाग का बर्ताव बदल जाता है?",
  },
  {
    _id: "i3MWtUchXxc",
    title: "React Redux with Redux Toolkit Complete in one Video (Hindi)",
    views: "38K",
    creator: "Geeky Shows",
    subscribers: "429 K",
    releaseTime: "1 year ago",
    genre: "programming",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLRruNCtXEbRiS21ZZVyNuLXNV6xhZMhb59YwcduIw=s88-c-k-c0x00ffffff-no-rj",
    description: "React Redux with Redux Toolkit Complete in one Video Hindi"
  },
  {
    _id: "XyqCFYnZ3EU",
    title: "Noise Sent me a Special Box! *Smart Glasses*",
    views: "1.4M",
    creator: "Tech burner",
    subscribers: "8.55M",
    releaseTime: "1 months ago",
    genre: "tech video",
    logoURL: "https://yt3.ggpht.com/ytc/AKedOLSLzBlLalLFEXgvGHr6f9yBm9Y8PrJMXZC_hxTTlQ=s88-c-k-c0x00ffffff-no-rj",
    description: "Ye BabuRao ka Chashma hai ! 🔥 Subscribe for Tabahi Videos"
  },
];